# Dockerfile
FROM openresty/openresty:alpine

COPY conf.d /etc/nginx/conf.d
COPY certs /etc/nginx/certs
COPY limit.lua /usr/local/openresty/nginx/resty/rate/limit.lua

EXPOSE 443
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]